### PR TITLE
evdev: Add options to swap touchscreen axes and apply min-max calibra…

### PR DESCRIPTION
**Pull request by stheil**
…tion values.

Implements the features mentioned in issue #37

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Please, add the config options to `lv_drv_conf_templ.h` and consistency the defines should  start with `EVDEV_...`.

**Comment by stheil** [comment]
Okay, I changed that. I think I just used the naming scheme from the "SCALE_EVDEV" options ^^

**Comment by kisvegabor** [comment]
Thank you! 
Oh really, `SCALE_EVDEV` should be `EVDEV_SCALE_...`. I didn't notice that earlier. I fixed it.

**Comment by stheil** [comment]
Compiles fine here. I don't have access to my hardware here to test it, but I don't see a reason this rename should break anything on the hardware.

**Comment by kisvegabor** [comment]
Great! Merged!

**Pull request merged**
