### PR TITLE
Patches to support Emscripten in `monitor` driver

### PR DESCRIPTION
**Pull request by embeddedt**

### CODE REVIEW

**Comment by kisvegabor** [comment]
I noticed two things:
1. As mentioned above, once you have `MONITOR_EMSCRIPTEN` it would be cleaner to use it later instead of `__EMSCRIPTEN__`
2. It seems you if we are using Emscripten you enable `MONITOR_APPLE`. It's not so clean. Is there any disadvantages to use `MONITOR_APPLE || MONITOR_EMSCRIPTEN`?

**Comment by embeddedt** [comment]
@kisvegabor Both of those are good points. I adjusted the `#ifdef`s.

**Comment by kisvegabor** [comment]
Perfect! Thank you!

**Comment by kisvegabor** [comment]
I usually delete feature branches on merge. Is it not a problem for you?

**Comment by embeddedt** [comment]
@kisvegabor No problem. There is no point keeping an outdated feature-specific branch around forever.

**Pull request merged**
