### PR TITLE
fbdev.c: fix using sec-screen-buffer crash

### PR DESCRIPTION
**Pull request by lgl88911**
Signed-off-by: Frank Li <lgl88911@163.com>

### CODE REVIEW

**Comment by embeddedt** [comment]
(cc @kisvegabor)

I am not sure of the exact scope of this change. Can you describe the issue you experienced in more detail? Why isn't `line_length * yres` equivalent to the size of your screen?

**Comment by lgl88911** [comment]
> (cc @kisvegabor)
> 
> I am not sure of the exact scope of this change. Can you describe the issue you experienced in more detail? Why isn't `line_length * yres` equivalent to the size of your screen?

In my platform, 
printf("%d(%d)(%d)x%d(%d)(%d), %dbpp linebyte: %d\n", vinfo.xres, vinfo.xoffset, vinfo.xres_virtual, vinfo.yres, vinfo.yoffset, vinfo.yres_virtual, vinfo.bits_per_pixel, finfo.line_length);
show blow:
1920(0)(1920)x1080(2160)(3240), 32bpp linebyte: 7680
current display from offset 2160, 
If only map 0~finfo.line_length * vinfo.yres,  during access "(act_x1 + vinfo.xoffset) + (y + vinfo.yoffset) * finfo.line_length / 4;" will out of memory cause crash。
So need map all framebuffer by using smem_len

**Comment by kisvegabor** [comment]
So the problem is that the offsets are not taken into account?

**Comment by lgl88911** [comment]
Yes, If framebuffer is double buffer and display screen point to secend buffer. Current code only map first buffer, but access secend buffer

**Comment by kisvegabor** [comment]
I see. `smem_len` seems also [standard field](https://www.kernel.org/doc/Documentation/fb/api.txt) in `fb_fix_screeninfo`. 

Merged, thank you!

**Pull request merged**
