### PR TITLE
implementation of libinput support

### PR DESCRIPTION
**Pull request by leiflm**
This is still work in progress.

### CODE REVIEW

**Comment by leiflm** [comment]
To elaborate on the reasons for implementing [libinput](https://www.freedesktop.org/wiki/Software/libinput/) support:
- Scraps unnecessary reimplementations of every functionality that is currently reimplemented using evdev raw (SCALE, CALIBRATION, etc.)
- More evdev flags/information (e.g. `absinfo.{minimum,maximum,resolution}`) are taken into consideration instead of relying on dedicated definitions (i.e. `#define`)

Using this, one will be able to [leverage hwdb](https://who-t.blogspot.com/2018/08/how-60-evdevhwdb-works.html) for hardware parameterization instead of recompiling the application for each input system.

**Comment by kisvegabor** [comment]
@leiflm 
Look good to me! 

Only one minor thing: `static` functions should go below the API functions. See this [Template](https://github.com/littlevgl/lvgl/blob/master/lv_misc/lv_templ.c).

**Comment by leiflm** [comment]
@kisvegabor thanks for the feedback. I'll get to do the cosmetics tomorrow, I hope.

ATM, however, it seems that the basic functionality does not work as expected. I'll hopefully get to work on that tomorrow, too.

**Comment by leiflm** [comment]
@kisvegabor do you need me to do anything else?

**Comment by kisvegabor** [comment]
Sorry, I didn't get notified when you marked the PR as ready.

Looks good to me. Thank you very much!

**Comment by leiflm** [comment]
no problem. I didn't want to push too hard.

Will this (sub) project see releases on its own?

**Comment by kisvegabor** [comment]
> Will this (sub) project see releases on its own?

There are no releases for this project now. The intention is to keep it always compatible with lvgl's `master` branch. The new breaking features are added into the current `dev-x.y` branch first and merged to master when the next version of lvgl is released.

**Pull request merged**
