### PR TITLE
Correct X, Y axis not inverting when EVDEV_XXX_MIN > EVDEV_XXX_MAX

### PR DESCRIPTION
**Pull request by criscola**

### CODE REVIEW

**Comment by criscola** [comment]
Ok so I should just replace the macro with ``lv_disp_get_xxx_res(drv->disp)`` in the four map functions so it can work when there are multiple displays?

**Comment by embeddedt** [comment]
Yes. Essentially, revert that portion of your diff. You can see how it should be [here](https://github.com/littlevgl/lv_drivers/pull/87/files) (in the red part).

**Comment by embeddedt** [comment]
Looks fine now. Thanks!

**Comment by criscola** [comment]
Thanks to you, this was my first pull-request yay!

**Pull request merged**
